# -*- coding: utf-8 -*-
"""task1_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B4AVUSUVeCRXwWapggn2JGkP0WV3QKEw
"""

class titanIndex:
    def __init__(self, titans, height, strength):
        self.titans = titans
        self.height = height
        self.strength = strength

    def TitanvsScout(self):  # Method , always takes self
        # scoutName = input("Name of Scout : ")
        # scoutStrength = int(input("Scout strength : "))
        scoutName = 'Levi'
        scoutStrength = 300
        winningStreak = 0
        if self.strength > scoutStrength:
            winningStreak = winningStreak + 1
            print(f"{self.titans} wins")
        elif self.strength < scoutStrength:
            print('{} wins'.format(scoutName))
        else:
            print('Draw')
        print(winningStreak)

    def TitanvsTitan(self):  #
        titanName = 'Armored Titan'
        titanStrength = 250
        if self.titans == titanName:
            print('Here , Titan does not have to fight with itself')
        elif self.strength > titanStrength:
            print(f"{self.titans} wins")
        elif self.strength < titanStrength:
            print('{} wins'.format(titanName))
        else:
            print('Draw')

print('\n')
print('Titan vs Scout')
foundingTitan = titanIndex("Founding Titan", 13, 350)
foundingTitan.TitanvsScout()

attackTitan = titanIndex("Attack Titan", 15, 275)
attackTitan.TitanvsScout()

colossalTitan = titanIndex("Colossal Titan", 60, 300)
colossalTitan.TitanvsScout()

print('\n')
print('Titan vs Titan')
attackTitan = titanIndex("Attack Titan", 15, 275)
attackTitan.TitanvsTitan()

armoredTitan = titanIndex("Armored Titan", 15, 250)
armoredTitan.TitanvsTitan()

jawTitan = titanIndex("Jaw Titan", 5, 235)
jawTitan.TitanvsTitan()

beastTitan = titanIndex("Beast Titan", 17, 250)
beastTitan.TitanvsTitan()
