# -*- coding: utf-8 -*-
"""task1_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sCx86JxGzh2VvmfynDBSMlq-M6LJWcX4
"""

class Titandex:
  def __init__(self,n,h,s):
    self.name=n
    self.height=h
    self.strength=s
    self.win_streak=0
  def TitanvsScout(self):
    print("enter number of battle",self.name,"and Scouts:")
    n=int(input())
    for i in range(n):
      print ("Enter Name of Scout and its Strength respectively:")
      scname=input()
      scstrength=int(input())
      if scstrength>self.strength:
        self.win_streak=0
        print ("Winner is:", scname)
        print ("Winning streak of",self.name, "is reset to zero")
      elif scstrength==self.strength:
        self.win_streak=0
        print ("Its a draw")
        print ("Winning streak of", self.name, "is reset to zero")
      else:
        self.win_streak=self.win_streak+1
        print ("winner is:",self.name)
        print ("Winning streak is: ",self.win_streak)
  def TitanvsTitan(self):
    print ("Input number of battles between", self.name, "and Titans:")
    n=(input())
    for i in range(n) :
      print ("Enter name of Titan and its strength respectively:")
      tname=input()
      tstrength=int(input())
      if tname==self.name:
        print("A Titan cannot fight itself")
      elif tstrength>self.strength:
        self.win_streak=0
        print ("winner:", tname)